/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imprenta.UI;

import imprenta.Maquina;
import imprenta.Trabajo;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sergio Amor Gutiérrez
 */
public class MainOperario extends javax.swing.JFrame {

    /**
     * Creates new form mainEmployee
     *
     * @param tipoOperario
     */
    public MainOperario(int tipoOperario) {
        initComponents();
        setVisible(true);
        setIconImage(new ImageIcon("assets/icons/format_paint_black_18x18.png").getImage());
//        if (tipoOperario != 2) {
//            tabOperaciones.removeTabAt(tipoOperario);
//        }
        setLocationRelativeTo(null);
        setTitle("Rodillo - " + Datos.opActual.getNombre() + " " + Datos.opActual.getApellidos());
        cargarTablaMaquinas();
        cargarTablaTrabajos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabOperaciones = new javax.swing.JTabbedPane();
        pnlImpresion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTrabajos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        btnMods = new javax.swing.JButton();
        btnValidar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMaquinas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaquinas = new javax.swing.JTable();
        btnReparar = new javax.swing.JButton();
        btnRellenar = new javax.swing.JButton();
        btnNuevoTrabajo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rodillo - NOMBRE OPERARIO");

        tblTrabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo relieve", "Fecha solicitud", "Fecha impresión", "Fecha recogida", "Listo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTrabajos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrabajosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTrabajos);
        if (tblTrabajos.getColumnModel().getColumnCount() > 0) {
            tblTrabajos.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblTrabajos.getColumnModel().getColumn(5).setPreferredWidth(40);
            tblTrabajos.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        jCheckBox1.setText("Pendientes");

        jCheckBox2.setText("Impresos");

        jCheckBox3.setText("Recogidos");

        jCheckBox4.setText("TipoImpresion1");

        jCheckBox5.setText("TipoImpresion2");

        jCheckBox6.setText("Modificados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMods.setText("Modificaciones");
        btnMods.setEnabled(false);
        btnMods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModsActionPerformed(evt);
            }
        });

        btnValidar.setText("Validar");
        btnValidar.setEnabled(false);
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.setEnabled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Nombre del trabajo");

        jLabel2.setText("Descripción  breve");

        javax.swing.GroupLayout pnlImpresionLayout = new javax.swing.GroupLayout(pnlImpresion);
        pnlImpresion.setLayout(pnlImpresionLayout);
        pnlImpresionLayout.setHorizontalGroup(
            pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpresionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlImpresionLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlImpresionLayout.createSequentialGroup()
                                .addComponent(btnMods)
                                .addGap(18, 18, 18)
                                .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnImprimir)))
                .addContainerGap())
        );
        pnlImpresionLayout.setVerticalGroup(
            pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpresionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlImpresionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlImpresionLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMods)
                            .addComponent(btnValidar))))
                .addContainerGap())
        );

        tabOperaciones.addTab("Operaciones de impresión", pnlImpresion);

        tblMaquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ubicación", "Compra", "Tipo impresión", "Modo impresión", "Volumen", "Capacidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMaquinas);

        btnReparar.setText("Reparar");
        btnReparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepararActionPerformed(evt);
            }
        });

        btnRellenar.setText("Rellenar");
        btnRellenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRellenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMaquinasLayout = new javax.swing.GroupLayout(pnlMaquinas);
        pnlMaquinas.setLayout(pnlMaquinasLayout);
        pnlMaquinasLayout.setHorizontalGroup(
            pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(pnlMaquinasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnReparar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)))
                .addContainerGap())
        );
        pnlMaquinasLayout.setVerticalGroup(
            pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaquinasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReparar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabOperaciones.addTab("Operaciones sobre máquinas", pnlMaquinas);

        btnNuevoTrabajo.setText("Registrar trabajo");
        btnNuevoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTrabajoActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        mnAbout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sergio\\OneDrive\\DAM1\\Entornos de desarrollo\\Proyecto\\Imprenta\\assets\\icons\\icons8-info-15.png")); // NOI18N
        mnAbout.setText("Sobre nosotros...");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenu2.add(mnAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabOperaciones)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabOperaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevoTrabajo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRellenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRellenarActionPerformed
        for (Iterator<Maquina> it = Datos.maquinas.iterator(); it.hasNext();) {
            Maquina next = it.next();
            if (next.getId() == (int) tblMaquinas.getValueAt(tblMaquinas.getSelectedRow(), 0)) {
                next.rellenar();
            }
        }
        Datos.guardarMaquinas();
        cargarTablaMaquinas();
    }//GEN-LAST:event_btnRellenarActionPerformed

    private void btnRepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepararActionPerformed
        new RepararMaquina(this, true).setVisible(true);
    }//GEN-LAST:event_btnRepararActionPerformed

    private void btnModsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModsActionPerformed
        new ModificacionesTrabajo(copiarTrabajoFila(tblTrabajos.getSelectedRow()));
    }//GEN-LAST:event_btnModsActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed

    }//GEN-LAST:event_mnAboutActionPerformed

    private void btnNuevoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTrabajoActionPerformed
        new NuevoTrabajo(this, true);
        cargarTablaTrabajos();
    }//GEN-LAST:event_btnNuevoTrabajoActionPerformed

    private void tblTrabajosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrabajosMouseClicked
        if (tblTrabajos.getSelectedRow() != -1) {
            habilitarOpciones();
        }
    }//GEN-LAST:event_tblTrabajosMouseClicked

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        for (Iterator<Trabajo> it = Datos.trabajos.iterator(); it.hasNext();) {
            Trabajo next = it.next();
            if (next.getId() == (int) tblTrabajos.getValueAt(tblTrabajos.getSelectedRow(), 0)) {
                next.setValido(true);
            }
        }
        Datos.guardarTrabajos();
        cargarTablaTrabajos();
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        for (Iterator<Trabajo> it = Datos.trabajos.iterator(); it.hasNext();) {
            Trabajo next = it.next();
            if (next.getId() == (int) tblTrabajos.getValueAt(tblTrabajos.getSelectedRow(), 0)) {
                next.imprimir();
            }
        }
        Datos.guardarTrabajos();
        cargarTablaTrabajos();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void habilitarOpciones() {
        btnMods.setEnabled(true);
        btnValidar.setEnabled(true);
        if ((boolean) tblTrabajos.getValueAt(tblTrabajos.getSelectedRow(), 5)) {
            btnImprimir.setEnabled(true);
            btnValidar.setEnabled(false);
        }
        if (tblTrabajos.getValueAt(tblTrabajos.getSelectedRow(), 3) != null) {
            btnImprimir.setEnabled(false);
        }
    }

    private void cargarTablaTrabajos() {
        Datos.cargarTrabajos();
        DefaultTableModel tm = (DefaultTableModel) tblTrabajos.getModel();
        for (int i = 0; i < tm.getRowCount(); i++) {
            tm.removeRow(i);
        }
        for (Trabajo t : Datos.trabajos) {
            tm.addRow(new Object[]{
                t.getId(),
                t.getRelieve(),
                t.getFechaSolicitud(),
                t.getFechaImpresion(),
                t.getFechaRecogida(),
                t.isValido()
            });
        }
        tblTrabajos.setModel(tm);
    }

    private void cargarTablaMaquinas() {
        Datos.cargarMaquinas();
        DefaultTableModel tm = (DefaultTableModel) tblMaquinas.getModel();
        for (int i = 0; i < tm.getRowCount(); i++) {
            tm.removeRow(i);
        }
        for (Maquina m : Datos.maquinas) {
            tm.addRow(new Object[]{
                m.getId(),
                m.getUbicacion(),
                m.getFechaCompra(),
                m.getTipoImpresion(),
                m.getModoImpresion(),
                m.getVolumen(),
                m.getCapacidadMax()
            });
        }
        tblMaquinas.setModel(tm);
    }

    private Trabajo copiarTrabajoFila(int row) {
        for (Trabajo t : Datos.trabajos) {
            if (t.getId() == (int) tblTrabajos.getValueAt(row, 0)) {
                return t;
            }
        }
        return null;
    }

    private Maquina copiarMaquinaFila(int row) {
        for (Maquina m : Datos.maquinas) {
            if (m.getId() == (int) tblMaquinas.getValueAt(row, 0)) {
                return m;
            }
        }
        return null;
    }

    public JFrame getThis() {
        return (JFrame) this;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainOperario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainOperario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainOperario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainOperario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainOperario(Integer.parseInt(args[0])).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMods;
    private javax.swing.JButton btnNuevoTrabajo;
    private javax.swing.JButton btnRellenar;
    private javax.swing.JButton btnReparar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JPanel pnlImpresion;
    private javax.swing.JPanel pnlMaquinas;
    private javax.swing.JTabbedPane tabOperaciones;
    private javax.swing.JTable tblMaquinas;
    private javax.swing.JTable tblTrabajos;
    // End of variables declaration//GEN-END:variables
}
